spring:
  sleuth:
    sampler:
      probability: 0

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.uuid}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

grpc:
  client:
    grpc-provider:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

# actuator info
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8
    name:grpc-comsumer
